### ISSUE TITLE
subscriptions module use-case

### ISSUE THREAD

**Issue by kbk574** [aztfmod/terraform-azurerm-caf#1228]
Hello!

I am using the subscriptions module as follows:

```
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

module "subscriptions" {
  source  = "aztfmod/caf/azurerm"
  version = "~>5.5.4"

  providers = {
    azurerm.vhub = azurerm // forced to add this
  }

  global_settings = var.global_settings

  subscriptions = {
    caf-01-sbx = {
      billing_account_name    = var.billing_account_name
      enrollment_account_name = var.enrollment_account_name
      name                    = "caf-01-sbx"
      workload                = "DevTest"
      management_group_id     = "Sandbox"
      tags = local.tags
    }
}
}
```

It works great. It creates the desired subscription instance, it creates the access token, and migrates the new sub to the desired management group, and the tags. All successfully!

I would like to download **only** the base required CAF module (subscriptions), and the dependent provider plugins.
However, when I configure it as above, the entire library of CAF modules are downloaded along with the entire provider plugins.

What am I doing incorrectly here? I would like to eliminate the non-required modules and the plugins altogether to keep the pipeline nimble. Also doing as above takes a lot longer for plan|apply.

Please advise!

Khalid

**Comment by arnaudlh** [comment]
hi @kbk574 glad to see it worked for you! 

my take here:

1. in version 5.6.0 the plan time is down to 1min so that probably solves the main issue. 

2. the supermodule is designed to have single entry point at the root (the way you use it) and do the association between components (the difficult part of the job :)). But if you want to disassemble it and use/consume only the submodule, no problem, but it would probably look like any random sample :)

**Comment by kbk574** [comment]
Thank you very much @arnaudlh, royally appreciate your response and guidance!
