### ISSUE TITLE
Azure function runtime version

### ISSUE THREAD

**Issue by brockneedscoffee** [aztfmod/terraform-azurerm-caf#365]
The runtime is not being set properly on the azure function

**Comment by adrian-gonzalez** [comment]
Hi @arnaudlh on our engagement we were unable to leverage CAF in order to create a Function App due to the below 
1. The CAF implementation of Azure Functions has a bug with the setting the managed identity.  
2. Azure Function App does appear to be configured properly. It does not start  
3. Azure Function App Module needs to be cleaned up.  

If someone starts to work on this bug please feel free to reach out so that we can elaborate on our observations. Once we conclude our engagement my crew would also be able to take a look at this.

**Comment by arnaudlh** [comment]
closing as not active. function examples been added by  @SergioMiyama
