### ISSUE TITLE
Support for Azurerm 3.x

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#904]
This epic is to track support for azurerm 3.0 work.
Current plan is to have it completed in 2204 releases.

**Comment by MarcelHeek** [comment]
Hi, 
I noticed this is still an ongoing issue. It is somewhat blocking for me/us as we use the caf-terraform-landingzones/caf_solution/add-ons/caf_eslz module to deploy the Enterprise Scale logic (Management Groups / Policies /etc.) Due to the breaking change (AzureRM provider version 3.0.2) introduced in the [v2.0.0](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5bUser-Guide%5d-Upgrade-from-v1.1.4-to-v2.0.0) release of caf_eslz module we are more or less stuck on the v1.4.0 of the caf-enterprise-scale module. So we are also stuck to using the AzureRM 2.99 provider version for all of our IaC configuration. And are subsequently several versions behind of the [current Enterprise Scale policy status](https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md).

We (and I guess many others) would be very happy if this could be fixed on a short notice. First question would be....When can we expect this issue to be fixed?

In our setup we deploy no resources (except management groups / policies) using the terraform-azurerm-caf-enterprise-scale module as we deployed connectivity/management resources already via the caf-terraform-landingzones/caf_solution and reference them via LZ/state references. Is there a way to only force the AzureRM v3.0.2 (or higher) to be used in case of the caf_solution\add-ons\caf_eslz scope and for all other scopes to keep using the AzureRM 2.99 version?

**Comment by JvHd-vw** [comment]
Any Update on this?

**Comment by piroinno** [comment]
Anyone know the recent status of this feature?

**Comment by arnaudlh** [comment]
Closing as supported started in 5.7.x
